### PR TITLE
add toHaveHtml matcher

### PR DESCRIPTION
**Pull request by haishengwu-okta**

### CODE REVIEW

**Comment by unindented** [comment]
I think this would be a very brittle selector. Using `toHaveClass` and `toHaveTag` seems like a better approach.

**Comment by unindented** [comment]
Fair enough. Thanks for the PR!

**Comment by haishengwu-okta** [comment]
@unindented 
appreciate your quick response!
will you release a new version as well?

**Comment by unindented** [comment]
Yup. I'm at work now, but I'll try to do it ASAP.

**Comment by unindented** [comment]
`2.1.0` published. Have a good weekend!

**Pull request merged**
